--liquibase formatted sql

--changeset egor:001-create-sellers
CREATE TABLE sellers (
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_info VARCHAR(255),
    registration_date TIMESTAMP NOT NULL
);
--rollback DROP TABLE sellers;