--liquibase formatted sql

--changeset egor:002-create-transactions
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    payment_type VARCHAR(32) NOT NULL,
    transaction_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_transactions_seller FOREIGN KEY (seller_id) REFERENCES sellers(id)
);

CREATE INDEX idx_transactions_seller_id ON transactions(seller_id);
CREATE INDEX idx_transactions_transaction_date ON transactions(transaction_date);
--rollback DROP TABLE transactions;
